# Generated by Django 4.1.5 on 2023-01-19 05:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
