# Generated by Django 4.1.5 on 2023-01-26 14:33

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=blog.models.upload_to),
        ),
    ]
