# Generated by Django 4.1.5 on 2023-01-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
